Repository akshaykhale1992/You-Dont-Need-image, pull requests merged in 2022-10, with the labels that each got.

#1 Smile Emoji add
  README.md
  examples/smile.html
  images/smile.png
Labels: hacktoberfest-accepted

#2 added CSS Star
  README.md
  examples/star.html
  images/star.png
Labels: hacktoberfest-accepted

#4 add contributors images to readme
  README.md
Labels: hacktoberfest-accepted

#7 Fixes Contributors image
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest

#9 Adds rainbow
  README.md
  examples/rainbow.html
  images/rainbow.png
Labels: hacktoberfest-accepted, hacktoberfest

#10 Image Size Optimized
  README.md
  images/eye-emoji.png
  images/heart.png
  images/rainbow.png
  images/star.png
Labels: hacktoberfest

#12 Adds Mario HTML and image
  README.md
  examples/mario.html
  images/mario.png
Labels: hacktoberfest-accepted, hacktoberfest

#13 Adds Snow icon html and css
  README.md
  examples/snow.html
  images/snow.png
Labels: hacktoberfest-accepted, hacktoberfest

#15 added penguin
  README.md
  examples/penguin.html
  images/penguin.png
Labels: hacktoberfest-accepted, hacktoberfest

#19 Added infinity symbol
  README.md
  examples/infinity.html
  images/infinity.png
Labels: hacktoberfest-accepted, hacktoberfest

#18 Added Cat
  README.md
  examples/cat.html
  images/cat.png
Labels: hacktoberfest-accepted, hacktoberfest
